### ISSUE TITLE
make failed on MacOS

### ISSUE THREAD

**Issue by vampirictutor** [linux-noah/homebrew-noah#2]
==> make install
Last 15 lines from /Users/dct/Library/Logs/Homebrew/noah/02.make:
    return CLOCK_MONOTONIC;
           ^
/tmp/noah-20171009-81105-1nepwii/noah-0.5.0/src/sys/time.c:190:12: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    return CLOCK_PROCESS_CPUTIME_ID;
           ^
/tmp/noah-20171009-81105-1nepwii/noah-0.5.0/src/sys/time.c:192:12: error: use of undeclared identifier 'CLOCK_THREAD_CPUTIME_ID'
    return CLOCK_THREAD_CPUTIME_ID;
           ^
5 errors generated.
make[2]: *** [CMakeFiles/noah.dir/src/sys/time.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 86%] Building C object CMakeFiles/noah.dir/src/proc/ptrace.c.o
/usr/local/Homebrew/Library/Homebrew/shims/super/clang  -I/tmp/noah-20171009-81105-1nepwii/noah-0.5.0/include  -Wall -Wextra -Wno-unused-parameter -std=gnu11 -DNDEBUG -O2   -o CMakeFiles/noah.dir/src/proc/ptrace.c.o   -c /tmp/noah-20171009-81105-1nepwii/noah-0.5.0/src/proc/ptrace.c
make[1]: *** [CMakeFiles/noah.dir/all] Error 2
make: *** [all] Error 2

**Comment by vmedlock** [comment]
Also failed today under El Capitan on a MacBook 5,1.
==========
Last 15 lines from ****/Library/Logs/Homebrew/noah/02.make:
           ^
/tmp/noah-20180128-7434-njea0l/noah-0.5.0/src/sys/time.c:188:12: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    return CLOCK_MONOTONIC;
           ^
/tmp/noah-20180128-7434-njea0l/noah-0.5.0/src/sys/time.c:190:12: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    return CLOCK_PROCESS_CPUTIME_ID;
           ^
/tmp/noah-20180128-7434-njea0l/noah-0.5.0/src/sys/time.c:192:12: error: use of undeclared identifier 'CLOCK_THREAD_CPUTIME_ID'
    return CLOCK_THREAD_CPUTIME_ID;
           ^
5 errors generated.
make[2]: *** [CMakeFiles/noah.dir/src/sys/time.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/noah.dir/all] Error 2
make: *** [all] Error 2

**Comment by equal-l2** [comment]
Which version of macOS are you using?
It builds fine on my MBP with macOS 10.13.3.

**Comment by vmedlock** [comment]
El Capitan, OS 10.11.xx (13, I think?) MacBook 5,1 is the late-2008 unibody model. Everything else I've asked it to run compiles fine, but there may be something in the hardware causing the failure.

**Comment by equal-l2** [comment]
It seems the problem is the version of your OS.

`CLOCK_MONOTONIC`, `CLOCK_PROCESS_CPUTIME_ID`, and `CLOCK_THREAD_CPUTIME_ID` are supposed to use with a function `clock_gettime`.

According to man page of `clock_gettime` on macOS 10.13.3, it `first appeared in Mac OSX 10.12`.
It means El Captian doesn't have `clock_gettime` and probably `CLOCK_*`.

Probably you should report this problem to [linux-noah/noah](https://github.com/linux-noah/noah/issues).

**Comment by equal-l2** [comment]
And also, you need a Mac which supports hypervisor to run noah.
It is reported noah doesn't run on MacBook 2010.
https://github.com/linux-noah/noah/issues/46

You can tell if your Mac supports hypervisor via this:
`﻿sysctl kern.hv_support`

If the output is `kern.hv_support: 1`, your Mac supports hypervisor.
Else if the output is `kern.hv_support: 0`, your Mac doesn't supports it.

**Comment by vmedlock** [comment]
There's the problem: no hypervisor support.  It's not a giant issue since I have Linux Mint installed in a dual-boot setup.  It's just that there are times when it would be convenient not having to reboot.

Thanks for your help!
